import axios from 'axios';
let data = JSON.stringify({
  "appId": "mheducation.com-1"
});

let config = {
  method: 'get',
  maxBodyLength: Infinity,
  url: 'https://api-test.twinex.io/api/perf-result/app',
  headers: { 
    'Content-Type': 'application/json', 
    'Authorization': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTBkZTc0ZjZmMTQ3NWMwMGVjZDA0ZmQiLCIkX18iOnsiYWN0aXZlUGF0aHMiOnsicGF0aHMiOnsicm9sZSI6ImluaXQiLCJfaWQiOiJpbml0Iiwib3JnSWQiOiJpbml0IiwiZmlyc3ROYW1lIjoiaW5pdCIsImxhc3ROYW1lIjoiaW5pdCIsInBob3RvIjoiaW5pdCIsImRlcGFydG1lbnQiOiJpbml0IiwiZGVzaWduYXRpb24iOiJpbml0IiwidXNlck5hbWUiOiJpbml0IiwiYXNzaWduZWRBc3NldHMiOiJpbml0IiwiZW1haWxBZGRyZXNzIjoiaW5pdCIsInBob25lTnVtYmVyIjoiaW5pdCIsImNvdW50cnkiOiJpbml0IiwibGFuZ3VhZ2UiOiJpbml0IiwidGltZXpvbmUiOiJpbml0IiwicGFzc3dvcmQiOiJpbml0IiwiY3JlYXRlZEF0IjoiaW5pdCIsInVwZGF0ZWRBdCI6ImluaXQiLCJfX3YiOiJpbml0In0sInN0YXRlcyI6eyJkZWZhdWx0Ijp7fSwiaW5pdCI6eyJfaWQiOnRydWUsIm9yZ0lkIjp0cnVlLCJmaXJzdE5hbWUiOnRydWUsImxhc3ROYW1lIjp0cnVlLCJwaG90byI6dHJ1ZSwicm9sZSI6dHJ1ZSwiZGVwYXJ0bWVudCI6dHJ1ZSwiZGVzaWduYXRpb24iOnRydWUsInVzZXJOYW1lIjp0cnVlLCJhc3NpZ25lZEFzc2V0cyI6dHJ1ZSwiZW1haWxBZGRyZXNzIjp0cnVlLCJwaG9uZU51bWJlciI6dHJ1ZSwiY291bnRyeSI6dHJ1ZSwibGFuZ3VhZ2UiOnRydWUsInRpbWV6b25lIjp0cnVlLCJwYXNzd29yZCI6dHJ1ZSwiY3JlYXRlZEF0Ijp0cnVlLCJ1cGRhdGVkQXQiOnRydWUsIl9fdiI6dHJ1ZX19fSwic2tpcElkIjp0cnVlfSwiJGlzTmV3IjpmYWxzZSwiX2RvYyI6eyJfaWQiOiI2NTBkZTc0ZjZmMTQ3NWMwMGVjZDA0ZmQiLCJvcmdJZCI6IjY1MGMyMWY0NDExZWZhYjJiZjM3YzFhYiIsImZpcnN0TmFtZSI6ImN4c2NvcmUiLCJsYXN0TmFtZSI6IiIsInBob3RvIjoiIiwicm9sZSI6ImFkbWluIiwiZGVwYXJ0bWVudCI6IiIsImRlc2lnbmF0aW9uIjoiIiwidXNlck5hbWUiOiJjeHNjb3JlIiwiYXNzaWduZWRBc3NldHMiOiIiLCJlbWFpbEFkZHJlc3MiOiIiLCJwaG9uZU51bWJlciI6IiIsImNvdW50cnkiOiIiLCJsYW5ndWFnZSI6IiIsInRpbWV6b25lIjoiIiwicGFzc3dvcmQiOiIkMmIkMTAkM0hnTmNpYXdEU1N2NE1zUFhwOTJRLjE4SXMwaXZHSldjcHh2dC8uVzRTWENRRFpuZ0dhWFciLCJjcmVhdGVkQXQiOiIyMDIzLTA5LTIyVDE5OjEzOjE5LjkxMloiLCJ1cGRhdGVkQXQiOiIyMDIzLTA5LTIyVDE5OjEzOjE5LjkxMloiLCJfX3YiOjB9LCJpYXQiOjE3MDc0MzQwOTd9.1tyrNxvcCWuAUPST5Wr8FYLq1xfKcxg7KU2-0cG7lnQ'
  },
  data : data
};

axios.request(config)
.then((response) => {
  console.log(JSON.stringify(response.data));
})
.catch((error) => {
  console.log(error);
});
